---
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
# Uncomment to set environment variables for services such as crio and kubelet.
# For example, configure the cluster to pull images via a proxy.
# environment: |
#   HTTP_PROXY=http://my-proxy:8000
#   HTTPS_PROXY=http://my-proxy:8000
#   NO_PROXY=127.0.0.1,localhost,master-node,node01,node02,node03
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  # Worker IPs are simply incremented from the control IP.
  control_ip: 10.0.0.10
  dns_servers:
    - 192.168.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    prefix: c
    count: 2
    cpu: 8
    memory: 4096
  workers:
    prefix: w
    count: 2
    cpu: 8
    memory: 2048
software:
  box: bento/ubuntu-22.04
  calico: 3.28.0
  #dashboard: 2.7.0
  kubernetes: 1.31.0-*

  os: xUbuntu_22.04
